### ISSUE TITLE
IntelliJ Import Fails 

### ISSUE THREAD

**Issue by Eternal-plasma** [Eternal-plasma/Arcane-Era#1]
All debugging attempts have failed so far--must use eclipse ide (for now)

**Comment by Lumineca** [comment]
I would like to help out with this in the near future (when I get back to my dev environment in a few days). Which version of Java are you using for this project?

**Comment by Eternal-plasma** [comment]
Java 1.8 (btw technically Minecraft forge 1.12.2 is not supported anymore but I wanted to make this anyway)

**Comment by Eternal-plasma** [comment]
the project imports everything but the resources

**Comment by Eternal-plasma** [comment]
then it breaks without them

**Comment by Lumineca** [comment]
sorry been away. taking a look now
